spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_lab
    username: sungyoung
    password:
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: auth-lab-secret-key-must-be-at-least-32-bytes-long!!
  expiration-ms: 6000000   # 1분(학습용)
  refresh-expiration-ms: 1209600000 # Refresh: 14일